name: staarm_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.12+13

environment:
  # sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  modal_bottom_sheet: ^2.0.0
  material_design_icons_flutter: 4.0.5755
  flutter_spinkit: ^4.1.2+1
  pinput: ^1.2.0
  carousel_slider: ^4.0.0
  carousel_images: ^1.1.2

  #arch / state management
  provider: ^6.0.1
  logging: 1.0.1

  #utils
  intl: ^0.17.0
  another_flushbar: ^1.10.22
  google_maps_flutter: ^2.0.3
  dio: ^4.0.0
  share: ^2.0.4
  equatable: ^2.0.3
  oktoast: ^3.0.0
  flutter_dotenv: ^3.1.0
  shimmer: ^2.0.0
  flutter_paystack: ^1.0.5+1
  flutter_datetime_picker: 1.5.0

  #native services
  shared_preferences: ^0.5.7+3
  # camera: ^0.9.4+6
  camera: 0.5.8+5
  path_provider: ^2.0.2
  flutter_google_places: ^0.3.0
  google_place: ^0.4.3
  image_picker: ^0.8.2
  cached_network_image: ^3.1.0+1
  location: ^4.3.0
  url_launcher: ^6.0.17
  intercom_flutter: ^5.3.0
  mixpanel_flutter: ^1.4.1
  sentry_flutter: ^6.2.2
  firebase_crashlytics: ^2.4.4
  firebase_analytics: ^8.2.0
  wechat_assets_picker: ^6.3.1
  sembast: ^3.1.0+2
  mati_plugin_flutter: ^2.6.0
  
  # camera: ^0.8.1+7

  #dependency injection
  get_it: ^4.0.4

  #notification
  firebase_core: ^1.1.0
  firebase_messaging: ^11.1.0

  # pusher
  flutter_pusher: 1.0.3
  flutter_svg: ^1.0.2


dependency_overrides:
  google_maps_webservice: ^0.0.19
  json_annotation: ^4.3.0
  meta: ^1.7.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/staarm_app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/car_features/
    - assets/images/menu_icons/
    - assets/images/mock_images/
    - assets/icons/
    - assets/icons/svgs/
    - assets/icons/trip_rules_icons/
    - assets/fonts/
    - assets/staarm_logo.png
    - assets/staarm_purple_logo.png
    - config/

  
  fonts:
    - family: PlusJakartaDisplay
      fonts:
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaDisplay/PlusJakartaDisplay-Italic.otf
          style: italic
          weight: 400

